python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":256,"d_model":64,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":256,"d_model":64,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":10,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":30,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":256,"d_model":64,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":256,"d_model":64,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":512,"d_model":128,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":1,"d_ff":512,"d_model":128,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":10,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":512,"d_model":64,"fusion_method":"","horizon":30,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":1e-05,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":1e-05,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":24,"lr":1e-05,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":360,"lr":1e-05,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/CrossLinear"

