python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":128,"d_model":128,"dropout":0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":168,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":128,"d_model":128,"dropout":0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":720,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":64,"d_model":128,"dropout":0.0,"e_layers":1,"horizon":10,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":30,"patience":5,"seq_len":60,"stride":30,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":64,"d_model":128,"dropout":0.0,"e_layers":1,"horizon":30,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":30,"patience":5,"seq_len":180,"stride":30,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.5,"batch_size":64,"d_ff":64,"d_model":128,"dropout":0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.5,"batch_size":64,"d_ff":64,"d_model":128,"dropout":0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":128,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":128,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.7,"batch_size":64,"d_ff":128,"d_model":512,"dropout":0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.7,"batch_size":64,"d_ff":128,"d_model":512,"dropout":0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.4,"batch_size":64,"d_ff":256,"d_model":64,"dropout":0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type1","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.4,"batch_size":64,"d_ff":256,"d_model":64,"dropout":0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type1","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.1,"e_layers":1,"horizon":10,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":60,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.1,"e_layers":1,"horizon":30,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":180,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.7,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.2,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":168,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.7,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.2,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":720,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":128,"dropout":0.2,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":168,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":128,"dropout":0.2,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":720,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.2,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":168,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0.2,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":8,"patience":5,"seq_len":720,"stride":8,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0,"e_layers":1,"horizon":24,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":168,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":128,"d_model":64,"dropout":0,"e_layers":1,"horizon":360,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":48,"patience":5,"seq_len":720,"stride":48,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DAG"

