python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":10,"lr":0.005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":60,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":30,"lr":0.005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":180,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.005,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.005,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":512,"d_model":256,"fusion_method":"","horizon":10,"lr":0.005,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":60,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":512,"d_model":256,"fusion_method":"","horizon":30,"lr":0.005,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":180,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":3e-05,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":3e-05,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":3e-05,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":3e-05,"mlp_hidden_dims":256,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":168,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":720,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DLinear"

