python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":1024,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":10,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":1024,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":30,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":256,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":256,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":10,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":256,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":256,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":30,"k":1,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":256,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":24,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":360,"k":2,"loss":"MAE","lr":0.0001,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/DUET"

