python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":2,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":2,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":2,"factor":3,"fusion_method":"","horizon":10,"lr":0.001,"mlp_hidden_dims":128,"n_heads":8,"norm":true,"patch_len":32,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":2,"factor":3,"fusion_method":"","horizon":30,"lr":0.001,"mlp_hidden_dims":128,"n_heads":8,"norm":true,"patch_len":32,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":10,"lr":0.001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":2048,"d_model":128,"e_layers":1,"factor":3,"fusion_method":"","horizon":30,"lr":0.001,"mlp_hidden_dims":256,"n_heads":2,"norm":true,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"n_heads":4,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"n_heads":4,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":64,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":64,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":2,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":512,"d_model":1024,"e_layers":1,"factor":3,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/PatchTST"

