python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":24,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":360,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":10,"lr":0.01,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":30,"lr":0.01,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":24,"lr":0.003,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":360,"lr":0.003,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":10,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":10,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":10,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":10,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":24,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":360,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":64,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":10,"lr":0.01,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":10,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":64,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":30,"lr":0.01,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":10,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TimeKAN"

