python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":10,"lr":0.001,"norm":true,"seq_len":60,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":30,"lr":0.001,"norm":true,"seq_len":180,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":512,"e_layers":1,"factor":3,"horizon":24,"lr":1e-05,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":512,"e_layers":1,"factor":3,"horizon":360,"lr":1e-05,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":10,"lr":0.0001,"norm":true,"seq_len":60,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":30,"lr":0.0001,"norm":true,"seq_len":180,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":512,"d_model":512,"e_layers":1,"factor":3,"horizon":24,"lr":1e-05,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":512,"d_model":512,"e_layers":1,"factor":3,"horizon":360,"lr":1e-05,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":24,"lr":0.0001,"norm":true,"seq_len":168,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":1,"factor":3,"horizon":360,"lr":0.0001,"norm":true,"seq_len":720,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/TimeXer"

