python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0003,"lradj":"sigmoid","mlp_hidden_dims":32,"norm":true,"num_epochs":20,"patience":3,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0003,"lradj":"sigmoid","mlp_hidden_dims":32,"norm":true,"num_epochs":20,"patience":3,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":128,"fusion_method":"","horizon":10,"lr":0.03,"lradj":"type3","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":128,"fusion_method":"","horizon":30,"lr":0.03,"lradj":"type3","mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0005,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0005,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.001,"lradj":"sigmoid","mlp_hidden_dims":64,"norm":true,"num_epochs":20,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.001,"lradj":"sigmoid","mlp_hidden_dims":64,"norm":true,"num_epochs":20,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":24,"lr":0.001,"lradj":"type3","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":168,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":360,"lr":0.001,"lradj":"type3","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":720,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":10,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":64,"norm":true,"num_epochs":20,"patience":5,"seq_len":60,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":30,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":64,"norm":true,"num_epochs":20,"patience":5,"seq_len":180,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/xPatch"

