python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 24, "lr": 0.0001, "mlp_hidden_dims": 512, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 360, "lr": 0.0001, "mlp_hidden_dims": 512, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 24, "lr": 0.001, "mlp_hidden_dims": 512, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 360, "lr": 0.001, "mlp_hidden_dims": 512, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 24, "lr": 0.005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 360, "lr": 0.005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 24, "lr": 0.0005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 360, "lr": 0.0005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 64, "horizon": 24, "lr": 0.0001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 64, "horizon": 360, "lr": 0.0001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 24, "lr": 0.0005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 32, "horizon": 360, "lr": 0.0005, "mlp_hidden_dims": 64, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 24, "lr": 0.0005, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 360, "lr": 0.0005, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 24, "lr": 0.001, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 360, "lr": 0.001, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 1024, "horizon": 24, "lr": 1e-05, "mlp_hidden_dims": 256, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 1024, "horizon": 360, "lr": 1e-05, "mlp_hidden_dims": 256, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 24, "lr": 0.0001, "norm": true, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 1, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 360, "lr": 0.0001, "norm": true, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 10, "lr": 0.001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 256, "horizon": 30, "lr": 0.001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 64, "horizon": 10, "lr": 0.001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI": 0, "batch_size": 32, "fusion_method": "mlp", "hidden_size": 64, "horizon": 30, "lr": 0.001, "mlp_hidden_dims": 256, "norm": true, "seq_len": 180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/Amplifier"
