python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0,"horizon":24,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0,"horizon":360,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0.2,"horizon":10,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":10,"patience":5,"rank":4,"seq_len":60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0.2,"horizon":30,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":30,"patience":5,"rank":4,"seq_len":180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":128,"d_model":128,"dropout":0.1,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":128,"d_model":128,"dropout":0.1,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":512,"dropout":0.1,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":512,"dropout":0.1,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0.1,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0.1,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":512,"dropout":0.1,"horizon":24,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":512,"dropout":0.1,"horizon":360,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":512,"dropout":0,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":64,"dropout":0,"horizon":10,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":10,"patience":5,"rank":4,"seq_len":60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":64,"d_model":64,"dropout":0,"horizon":30,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":30,"patience":5,"rank":4,"seq_len":180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.2,"horizon":24,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":512,"dropout":0.2,"horizon":360,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0.1,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0.1,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":128,"d_model":256,"dropout":0,"horizon":24,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":128,"d_model":256,"dropout":0,"horizon":360,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0,"horizon":24,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"rank":4,"seq_len":168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/GCGNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "GCGNet.GCGNet" --model-hyper-params '{"batch_size":64,"d_ff":256,"d_model":64,"dropout":0,"horizon":360,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":360,"patience":5,"rank":4,"seq_len":720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/GCGNet"

