python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.3, "e_layers": 1, "horizon": 24, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.3, "e_layers": 1, "horizon": 360, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.3, "e_layers": 1, "horizon": 24, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.3, "e_layers": 1, "horizon": 360, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 24, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 360, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 1024, "d_layers": 1, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 24, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 4, "covariate_dim": 2, "d_ff": 1024, "d_layers": 1, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 360, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 32, "d_layers": 3, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 24, "lr": 0.0005, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 32, "d_layers": 3, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 360, "lr": 0.0005, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 7, "covariate_dim": 5, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 24, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 7, "covariate_dim": 5, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 360, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 24, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 360, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 24, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 360, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 24, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 360, "lr": 0.001, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 24, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 168}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 512, "c_out": 8, "covariate_dim": 6, "d_ff": 256, "d_layers": 2, "d_model": 256, "dropout": 0.1, "e_layers": 2, "horizon": 360, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 720}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 32, "d_layers": 2, "d_model": 96, "dropout": 0.3, "e_layers": 1, "horizon": 10, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 32, "d_layers": 2, "d_model": 96, "dropout": 0.3, "e_layers": 1, "horizon": 30, "lr": 0.01, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 3, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 10, "lr": 0.0005, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 60}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size": 128, "c_out": 4, "covariate_dim": 2, "d_ff": 256, "d_layers": 3, "d_model": 256, "dropout": 0.1, "e_layers": 1, "horizon": 30, "lr": 0.0005, "norm": true, "num_epochs": 10, "patience": 5, "seq_len": 180}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/TiDE"
