python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":96,"lr":0.0001,"mlp_hidden_dims":512,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":192,"lr":0.0001,"mlp_hidden_dims":512,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":336,"lr":0.0001,"mlp_hidden_dims":512,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":720,"lr":0.0001,"mlp_hidden_dims":512,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":96,"lr":0.0005,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":192,"lr":0.0005,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":336,"lr":0.0005,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":720,"lr":0.0005,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":512,"horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":1024,"horizon":96,"lr":0.0001,"mlp_hidden_dims":96,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":1024,"horizon":192,"lr":0.0001,"mlp_hidden_dims":96,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":1024,"horizon":336,"lr":0.0001,"mlp_hidden_dims":96,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":1,"batch_size":32,"fusion_method":"","hidden_size":1024,"horizon":720,"lr":0.0001,"mlp_hidden_dims":96,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":96,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":192,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":336,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":720,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":96,"lr":0.02,"mlp_hidden_dims":128,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":192,"lr":0.02,"mlp_hidden_dims":128,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":336,"lr":0.02,"mlp_hidden_dims":128,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":720,"lr":0.02,"mlp_hidden_dims":128,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":96,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":192,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":336,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "amplifier.Amplifier" --model-hyper-params '{"SCI":0,"batch_size":32,"fusion_method":"","hidden_size":64,"horizon":720,"lr":0.0001,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/Amplifier"

