python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":1,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":1,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":256,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":96,"lr":1e-05,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":192,"lr":1e-05,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":336,"lr":1e-05,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CrossLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.CrossLinear" --model-hyper-params '{"alpha":0.5,"batch_size":16,"beta":0.5,"d_ff":1024,"d_model":64,"fusion_method":"","horizon":720,"lr":1e-05,"mlp_hidden_dims":64,"norm":true,"num_epochs":10,"patch_len":8,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/CrossLinear"

