python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":1024,"dropout":0,"e_layers":2,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":2,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":1024,"dropout":0,"e_layers":2,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":2,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":1024,"dropout":0,"e_layers":2,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":2,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":1024,"dropout":0,"e_layers":2,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":2,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":1,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":1,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":1,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":1,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":1,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.3,"e_layers":3,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":1e-05,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":1,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.3,"e_layers":3,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":1e-05,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":1,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.3,"e_layers":3,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":1e-05,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":1,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.3,"e_layers":3,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":1e-05,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.1,"e_layers":2,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.1,"e_layers":2,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.1,"e_layers":2,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.1,"e_layers":2,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.95,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":2,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":2,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":2,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.8,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0.2,"e_layers":2,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":16,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.6,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":96,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":192,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":336,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DAG"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "dag.DAG" --model-hyper-params '{"alpha":0.9,"batch_size":64,"d_ff":512,"d_model":256,"dropout":0,"e_layers":1,"horizon":720,"infer_use_future":0,"loss":"MAE","lr":0.0001,"lradj":"type3","n_heads":4,"norm":true,"num_epochs":50,"patch_len":24,"patience":5,"seq_len":96,"use_c":1,"use_c_exog":1,"use_t":1,"use_t_exog":1}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DAG"

