python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.003,"mlp_hidden_dims":512,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0005,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":2048,"d_model":512,"fusion_method":"","horizon":96,"lr":0.0001,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":2048,"d_model":512,"fusion_method":"","horizon":192,"lr":0.0001,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":2048,"d_model":512,"fusion_method":"","horizon":336,"lr":0.0001,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"d_ff":2048,"d_model":512,"fusion_method":"","horizon":720,"lr":0.0001,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0005,"mlp_hidden_dims":64,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DLinear"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.DLinear" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":3e-05,"mlp_hidden_dims":32,"norm":true,"period_len":24,"seq_len":96,"station_lr":0.0001,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DLinear"

