python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":256,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":2,"loss":"MAE","lr":0.001,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":2,"loss":"MAE","lr":0.01,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":2,"loss":"MAE","lr":0.01,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":2,"loss":"MAE","lr":0.01,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":2,"loss":"MAE","lr":0.01,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":512,"dropout":0.2,"e_layers":2,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":2,"loss":"MAE","lr":0.0005,"lradj":"type1","mlp_hidden_dims":64,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":1024,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":2,"loss":"MAE","lr":0.0003,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":1024,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":2,"loss":"MAE","lr":0.0003,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":1024,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":2,"loss":"MAE","lr":0.0003,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":1024,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":2,"loss":"MAE","lr":0.0003,"lradj":"type1","mlp_hidden_dims":128,"n_heads":1,"norm":true,"num_epochs":100,"num_experts":4,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":32,"d_ff":512,"d_model":512,"dropout":0.5,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":1,"loss":"MAE","lr":0.0001,"lradj":"type1","n_heads":1,"norm":true,"num_epochs":100,"num_experts":2,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":96,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":192,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":336,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "duet.DUET" --model-hyper-params '{"CI":1,"batch_size":64,"d_ff":1024,"d_model":128,"dropout":0.2,"e_layers":1,"factor":3,"fc_dropout":0.1,"fusion_method":"","horizon":720,"k":2,"loss":"MAE","lr":5e-05,"lradj":"type1","mlp_hidden_dims":32,"n_heads":16,"norm":true,"num_epochs":100,"num_experts":8,"patch_len":48,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/DUET"

