python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":128,"n_heads":4,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":256,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"n_heads":8,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":96,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":192,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":336,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.PatchTST" --model-hyper-params '{"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"fusion_method":"","horizon":720,"lr":0.0001,"n_headers":2,"norm":true,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/PatchTST"

