python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":8,"covariate_dim":6,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.1,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":64,"c_out":322,"covariate_dim":320,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":64,"c_out":322,"covariate_dim":320,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":64,"c_out":322,"covariate_dim":320,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":64,"c_out":322,"covariate_dim":320,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":9,"covariate_dim":7,"d_ff":1024,"d_layers":1,"d_model":256,"dropout":0.1,"e_layers":3,"horizon":96,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":9,"covariate_dim":7,"d_ff":1024,"d_layers":1,"d_model":256,"dropout":0.1,"e_layers":3,"horizon":192,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":9,"covariate_dim":7,"d_ff":1024,"d_layers":1,"d_model":256,"dropout":0.1,"e_layers":3,"horizon":336,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":9,"covariate_dim":7,"d_ff":1024,"d_layers":1,"d_model":256,"dropout":0.1,"e_layers":3,"horizon":720,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":8,"c_out":863,"covariate_dim":861,"d_ff":128,"d_layers":3,"d_model":128,"dropout":0.3,"e_layers":2,"horizon":96,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":8,"c_out":863,"covariate_dim":861,"d_ff":128,"d_layers":3,"d_model":128,"dropout":0.3,"e_layers":2,"horizon":192,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":8,"c_out":863,"covariate_dim":861,"d_ff":128,"d_layers":3,"d_model":128,"dropout":0.3,"e_layers":2,"horizon":336,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":8,"c_out":863,"covariate_dim":861,"d_ff":128,"d_layers":3,"d_model":128,"dropout":0.3,"e_layers":2,"horizon":720,"lr":0.001,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":22,"covariate_dim":20,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":96,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":22,"covariate_dim":20,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":192,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":22,"covariate_dim":20,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":336,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TiDE"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --adapter "transformer_adapter" --model-name "time_series_library.TiDE" --model-hyper-params '{"batch_size":512,"c_out":22,"covariate_dim":20,"d_ff":256,"d_layers":2,"d_model":256,"dropout":0.1,"e_layers":1,"horizon":720,"lr":0.01,"norm":true,"num_epochs":10,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TiDE"

