python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":96,"lr":1e-05,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":192,"lr":1e-05,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":336,"lr":1e-05,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":720,"lr":1e-05,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"horizon":96,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"horizon":192,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"horizon":336,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":1,"factor":3,"horizon":720,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":96,"lr":0.0001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":192,"lr":0.0001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":336,"lr":0.0001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":720,"lr":0.0001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":128,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":96,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":128,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":192,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":128,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":336,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":128,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":720,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":96,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":192,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":336,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":720,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":96,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":192,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":336,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":64,"d_ff":512,"d_model":256,"e_layers":2,"factor":3,"horizon":720,"lr":0.001,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":96,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":192,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":336,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":16,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":720,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":96,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":192,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":336,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeXer"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timexer.TimeXer" --model-hyper-params '{"batch_size":32,"d_ff":1024,"d_model":512,"e_layers":2,"factor":3,"horizon":720,"norm":true,"seq_len":96,"use_future":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeXer"

