python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":1,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":1,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":1,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":1,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":256,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":16,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":16,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":16,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":16,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.0005,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":64,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":128,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":4,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.01,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":4,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.01,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":4,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.01,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":4,"begin_order":0,"d_ff":32,"d_model":16,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.01,"norm":true,"num_epochs":10,"patience":10,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":96,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":192,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":336,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeKAN"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "timekan.TimeKAN" --model-hyper-params '{"batch_size":32,"begin_order":0,"d_ff":16,"d_model":32,"down_sampling_layer":1,"down_sampling_window":2,"e_layers":2,"fusion_method":"","horizon":720,"lr":0.0001,"mlp_hidden_dims":32,"norm":true,"num_epochs":10,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/TimeKAN"

