python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0001,"lradj":"type3","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":96,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":192,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":336,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":720,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":256,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":96,"lr":0.0005,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":192,"lr":0.0005,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":336,"lr":0.0005,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":720,"lr":0.0005,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":16,"fusion_method":"","horizon":96,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":16,"fusion_method":"","horizon":192,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":16,"fusion_method":"","horizon":336,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":16,"fusion_method":"","horizon":720,"lr":0.0005,"mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":96,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":192,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":336,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":64,"fusion_method":"","horizon":720,"lr":0.0005,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":4,"fusion_method":"","horizon":96,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":4,"fusion_method":"","horizon":192,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":4,"fusion_method":"","horizon":336,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":4,"fusion_method":"","horizon":720,"lr":0.0001,"lradj":"sigmoid","mlp_hidden_dims":128,"norm":true,"num_epochs":20,"patience":5,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":96,"lr":0.001,"lradj":"type3","mlp_hidden_dims":1024,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":192,"lr":0.001,"lradj":"type3","mlp_hidden_dims":1024,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":336,"lr":0.001,"lradj":"type3","mlp_hidden_dims":1024,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size":32,"fusion_method":"","horizon":720,"lr":0.001,"lradj":"type3","mlp_hidden_dims":1024,"norm":true,"num_epochs":20,"patience":3,"seq_len":96,"use_future_exog":0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"

